version: '3'
services:
  patientdocumentsearchapp:
        container_name: patientdocumentsearchapp
        build: .
        ports:
          - "8080:8080"
        depends_on:
          - mysqldb
  mysqldb:
   container_name: mysqldb
   image: mysql:8.0.19
   restart: always
   environment:
        - MYSQL_ROOT_PASSWORD=root@123
        - MYSQL_USER=root
        - MYSQL_DATABASE=patientrecord
   volumes:
         - ./init_mysql.sql:/docker-entrypoint-initdb.d/init_mysql.sql
   ports:
   - "3306:3306"
